### ISSUE TITLE
How to run a command after install

### ISSUE THREAD

**Issue by nkaramolegos** [vrest-io/vutil#2]
How can I user curl to execute ls?

**Comment by jangid** [comment]
After cloning the repository run the following command inside the root project directory:
`PORT=4080 node server.js`

**Comment by nkaramolegos** [comment]
I already did that. How can execute a command though rest api?

**Comment by dheerajaggarwal** [comment]
For executing the system command through REST API, you may use the following API endpoint:
POST `{{baseURL}}/execute/command`

and provide a request body parameter named as `command` and provide the system command as the parameter value.

For more information, you may look at this guide link:
https://docs.optimizory.com/x/JIXB

**Comment by dhiraj69** [comment]
i managed to install vutil but when i try and execute a command i get the following: 
![image](https://user-images.githubusercontent.com/1945338/184241530-556feb42-fb21-4e1c-8c96-aac0bb2f7845.png)

{"code":"MethodNotAllowedError","message":"GET is not allowed"}

i also dont see to get the landing page when i brower to the base url

**Comment by dheerajaggarwal** [comment]
Hi Dhiraj, GET method is not allowed for executing the system command, use POST instead. For executing the system command through REST API, you may use the following API endpoint:
POST {{baseURL}}/execute/command

and provide a request body parameter named as command and provide the system command as the parameter value.

For more information, you may look at this guide link:
https://docs.optimizory.com/x/JIXB

**Comment by dhiraj69** [comment]
> Hi Dhiraj, GET method is not allowed for executing the system command, use POST instead. For executing the system command through REST API, you may use the following API endpoint: POST {{baseURL}}/execute/command
> 
> and provide a request body parameter named as command and provide the system command as the parameter value.
> 
> For more information, you may look at this guide link: https://docs.optimizory.com/x/JIXB

Thanks Dheeraj.


Would have been good if there was a swagger UI also integrated into this code base. Is there a plan for it?

**Comment by dheerajaggarwal** [comment]
You're welcome.

In the code base, there is already a Swagger file attached in the repository. You may open that file in the Swagger Editor.
https://github.com/vrest-io/vutil/blob/master/vutil-swagger.yaml
